### ISSUE TITLE
Is there a reference for this code?

### ISSUE THREAD

**Issue by zyueyue7** [omkar-commits/Detereminig-Trustworhiness-of-IoT-crowdsensing-Data#2]
Hello, I downloaded your code, but because of my limited level, I can't understand some of them. So I would you like to ask the reference documents for the code? Or the code explanation can be used. I hope to get your reply. Thank you

**Comment by omkar-commits** [comment]
Hi,

1. Most of the documents are output results after running the algorithm on
either jupyter notebook or Spyder.  you can check the entire code in
Trustworthiness Algorithm.ipynb or Trust_alogorith.py file.
2. Outputs are obtained in XLX format for better visualization and
understanding.

3. input files are in JSON format.
I have created input data based on my understanding and research as
practically Crowd Sensing data collection requires more memory and
applications and due to time constraints I created data for 200 people to
test my algorithm.

4. Running on SUMO requires configuration steps. You can refer to the SUMO
website or any available resources online. There  are different ways to run
an algorithm on SUMO. or you can also create your own traffic environment
and test it using SUMO.

5. I have also updated my repository with my project document in
PDF format. Feel Free to refer. I hope it helps.

Regards,
Omkar
